import type { Metadata } from "next";
import "./globals.css";
import  AppSidebar  from "@/components/SideBar";

export const metadata: Metadata = {
  title: "MemeWebsite",
  description: "Generated by create next app",
};


export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
      <main>
        {children}
      </main>
    </body>
    </html>
  )
}

